### ISSUE TITLE
Able to create account without fulfilling username reqs.

### ISSUE THREAD

**Issue by bfforsythe** [nidamon/CS372#14]
I was able to create the account "greenBeans" which allowed me to login and view movies, which does not adhere to the username requirements.

**Comment by nidamon** [comment]
What username requirement does it not adhere to?

**Comment by Willg3D** [comment]
Issue should be resolved please check
Requirements are:

- length >=8
- at least 1 cap
- at least 1 num
- at least 1 special char
- no spaces
