### ISSUE TITLE
Branding on each page?

### ISSUE THREAD

**Issue by bfforsythe** [nidamon/CS372#15]
I can't come up with a good implementation, but maybe you could have your logo on each page? like landing, login, and viewpage

**Comment by Willg3D** [comment]
Added logo to home.html, loginpage.html, signup.html, videoupload.html, and landingpage.
See if it is to your liking.

**Comment by bfforsythe** [comment]
I do like the logo, it's spiffy. Could you make it so clicking the image takes you to the homepage, regardless of which page you're on?

**Comment by bfforsythe** [comment]
i like that the images get a little bigger which allows the user to know its clickable, heck yeah
