### ISSUE TITLE
Unique passwords do not work

### ISSUE THREAD

**Issue by bfforsythe** [nidamon/CS372#2]
When signing up, I can't create the password I want. for example, P4ssw0rdsssss does not work, it complains about special characters, even though there are not.
![image](https://user-images.githubusercontent.com/77409666/227663939-0e69527a-728d-4615-8895-5e2d99b58b09.png)

**Comment by nidamon** [comment]
This should be fixed with the latest update to signup.html.

**Comment by bfforsythe** [comment]
epic
