### ISSUE TITLE
Hardcoded video width and height

### ISSUE THREAD

**Issue by bfforsythe** [nidamon/CS372#20]
videoModule.js , line 69
home.html , line 38
notInMyHouse.html , line 22
booooooo get it defined at the beginning of your code, no width="560px" height="300px"

**Comment by Willg3D** [comment]
Addressed complaints on hardcoded values with no variable names; however, variable names are at the bottom of HTML pages due to how the code is set up. For videoModule variable names are at the top.

**Comment by bfforsythe** [comment]
yep, looks modular
