### ISSUE TITLE
Variable Names

### ISSUE THREAD

**Issue by segallagher** [nidamon/CS372#21]
server.js line 15: what is q?
server.js line 109: uname not following camel case uName could replace

**Comment by nidamon** [comment]
q is now query and uname at line 109 and the rest of the function has been changed to uName to fit camelCase practices.

**Comment by segallagher** [comment]
not sure if this is a variable name but 
server.js line 263: 'qs' is not easily understood
server.js line 529: 'qs' is not easily understood
