### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by segallagher** [nidamon/CS372#23]
credentialModule.js line 5: remember to remove after code is simplified
credentialModule.js line 9: variable names should be self-evident and not have an explainer.
credentialModule.js line 137, 145,160: could be replaced with "// in millis" instead of a two line comment
credentialModule.js line 101: unnecessary comment
credentialModule.js line 129: unnecessary comment
credentialModule.js line 156: unnecessary comment

databaseModule.js line 3: unnecessary comment
databaseModule.js line 20: unnecessary comment
databaseModule.js line 31: unnecessary comment
databaseModule.js line 41: unnecessary comment
databaseModule.js line 135: unnecessary comment
databaseModule.js line 138: unnecessary comment
databaseModule.js line 191: unnecessary comment
databaseModule.js line 249: unnecessary comment
databaseModule.js line 276: change videoname to videoName
databaseModule.js line 289: unnecessary comment
databaseModule.js line 290: unnecessary comment
databaseModule.js line 302: unnecessary comment

videoModule.js line 28: unnecessary comment 
videoModule.js line 30: unnecessary comment 
videoModule.js line 32: unnecessary comment 
videoModule.js line 93: unnecessary comment 

server.js line 105: unnecessary comment 
server.js line 110: unnecessary comment 
server.js line 115: unnecessary comment 
server.js line 120: unnecessary comment 
server.js line 200: unnecessary comment 
server.js line 204: unnecessary comment 
server.js line 210: unnecessary comment 
server.js line 240: unnecessary comment 
server.js line 245: unnecessary comment 
server.js line 252: unnecessary comment (at top of definition)
server.js line 253: unnecessary comment (at top of definition)
server.js line 254: unnecessary comment 
server.js line 263: unnecessary comment (at top of definition)
server.js line 266: unnecessary comment 
server.js line 294: unnecessary comment (at top of definition)
server.js line 352: unnecessary comment 
server.js line 377: unnecessary comment 
server.js line 419: unnecessary comment 
server.js line 424: unnecessary comment 
server.js line 425: unnecessary comment 
server.js line 437: unnecessary comment 
server.js line 438: unnecessary comment 
server.js line 450: unnecessary comment 
server.js line 454: unnecessary comment 
server.js line 456: unnecessary comment 
server.js line 465: No clue what it means, but maybe that's because I don't have the prerequisite knowledge
server.js line 541: unnecessary comment 
server.js line 542: unnecessary comment 
server.js line 546: unnecessary comment 
server.js line 548: comment doesn't add information
server.js line 551: unnecessary comment 
server.js line 554: unnecessary comment 
server.js line 613: unnecessary comment

**Comment by segallagher** [comment]
I might've been a little overzealous, some of these may be important. If any of these comments are important feel free leave those in.

**Comment by segallagher** [comment]
all the line placements are off now

**Comment by segallagher** [comment]
updated comment lines for current version of repo

**Comment by Willg3D** [comment]
Thanks for the updated list.
Comments that I felt were unnecessary have now been removed.
