### ISSUE TITLE
Variable like names

### ISSUE THREAD

**Issue by segallagher** [nidamon/CS372#24]
not sure if this is a variable name but
server.js line 263: 'qs' is not easily understood
server.js line 529: 'qs' is not easily understood

(I could not reopen the other variable names issue) and I'm not sure if these count as variables or names

**Comment by segallagher** [comment]
credentialModule.js line 155: "no" could be replaced with unlocked or notLocked

**Comment by nidamon** [comment]
'qs' is now 'questions'
'ans' in now 'answers'
'no' is now either 'locked' or 'notLoggedIn'
'yes' is now either 'notLocked' or 'loggedIn'

Feel free to check.
