### ISSUE TITLE
long function

### ISSUE THREAD

**Issue by segallagher** [nidamon/CS372#26]
videoModule.js createVideoList is 33 lines long. Lots of whitespace so it should be easy to reduce a little

**Comment by nidamon** [comment]
createVideoList should now be within an acceptable range of length.

**Comment by nidamon** [comment]
I will look into using enum to make createServer in server.js more readable and efficient.

**Comment by nidamon** [comment]
Changed the directing code to use a switch instead of if else statements.

**Comment by segallagher** [comment]
directOnRequest(), previously createServer(), is now much nicer to read and is within line limit.
