### ISSUE TITLE
Add a dropdown for genre search 

### ISSUE THREAD

**Issue by segallagher** [nidamon/CS372#29]
Need a dropdown for genre search. Populate it with each genre that exists in the database.
The content editor should be able to upload whatever genre/genres they want for the database to dynamically search through.

**Comment by nidamon** [comment]
A dropdown has been added to the upload page and a dropdown has replaced the genre search bar on the landing page.
The content editor can enter new and old genres via the genre text field as well as use the dropdown to add existing genres on upload.

**Comment by segallagher** [comment]
The dropdown for genre search works. However the dropdown to add previous genres on video upload does not.

Also be sure to add the changes to the database requirements (genreData) to the README

**Comment by nidamon** [comment]
The dropdown on the video upload page should work now. Also, the database requirements in the README has been updated with "genreData".
