### ISSUE TITLE
Server Crash after creating new account.

### ISSUE THREAD

**Issue by bfforsythe** [nidamon/CS372#4]
Creating account after logging onto website through 10.XX.XX, after sucessful account creation, redirect crashes.

**Comment by nidamon** [comment]
@bfforsythe Can you give more information on the context?

**Comment by bfforsythe** [comment]
@nidamon I believe with the migration over to chillflix.william.... etc, this problem has been nullified, probably good to close

**Comment by Willg3D** [comment]
I will close this issue; if any crashes happen, please resubmit the issue. It seems this might have been a minor glitch when testing the server on campus.
